version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    environment:
    - IMAGE: alpine
    - TAG: '3.8'
    machine:
      image: ubuntu-1604:201903-01
    steps:
    - run:
        command: docker pull ${IMAGE}:${TAG}
    - run:
        name: Pull and Scan
        command: 
          wget https://community-aqua-reports.s3.amazonaws.com/scannercli && 
          chmod +x scannercli &&
          mkdir /tmp/artifacts &&
          sudo mkdir /opt/aquascans &&
          sudo chmod 777 /opt/aquascans &&
          ./scannercli scan --host $AQUA_SERVER --local ${IMAGE}:${TAG} --dockerless --user ali@aquasec.com --password Tumkish!225
          #--htmlfile /tmp/artifacts/${IMAGE}-${TAG}.html
    #- store_artifacts:
      #  path: /tmp/artifacts
